name: Autoupdater

# Run every day at 2AM and 2PM
on:
  schedule:
  - cron: "0 2,14 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: powershell-yaml
          shell: powershell, pwsh

      - name: Run script
        id: checker
        run: ./checker.ps1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update ${{ steps.checker.outputs.changed }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Automatic update of ${{ steps.checker.outputs.changed }}
          body: |
            Hello there üëã
            üö® New ${{ steps.checker.outputs.version }} of ${{ steps.checker.outputs.module }} detected 
            ‚úÖ Please review my edit and merge
            ‚è∞ I'll check all the modules tomorrow
            
            <sub>Auto-generated by [create-pull-request][1]</sub>

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            autoupdate
          draft: false
          base: dev
          branch: autoupdater
